-- Pawdar v5 barangay seed data (Batangas Province)
-- Generated from docs/Batangas_Cities_and_Barangays.md
-- Run AFTER schema-v5-locations.sql (creates city/barangay tables).
-- Safe to re-run: uses ON DUPLICATE KEY UPDATE.

-- Ensure tables exist (skip if you already ran schema-v5-locations.sql)
-- Pawdar v5: normalized city/barangay reference tables (Batangas Province)
-- Seed data: import schema-v5-barangays-seed.sql via phpMyAdmin (InfinityFree)
-- Or locally: php sql/import-barangays.php

CREATE TABLE IF NOT EXISTS city (
    city_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    UNIQUE KEY uniq_city_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS barangay (
    barangay_id INT AUTO_INCREMENT PRIMARY KEY,
    city_id INT NOT NULL,
    name VARCHAR(120) NOT NULL,
    UNIQUE KEY uniq_city_barangay (city_id, name),
    CONSTRAINT fk_barangay_city FOREIGN KEY (city_id) REFERENCES city(city_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO city (city_id, name) VALUES (1, 'Batangas City')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(1, 'Alangilan'),
(1, 'Balagtas'),
(1, 'Balete'),
(1, 'Banaba Center'),
(1, 'Banaba Ibaba'),
(1, 'Banaba Kanluran'),
(1, 'Banaba Silangan'),
(1, 'Barangay 1 (Poblacion)'),
(1, 'Barangay 2 (Poblacion)'),
(1, 'Barangay 3 (Poblacion)'),
(1, 'Barangay 4 (Poblacion)'),
(1, 'Barangay 5 (Poblacion)'),
(1, 'Barangay 6 (Poblacion)'),
(1, 'Barangay 7 (Poblacion)'),
(1, 'Barangay 8 (Poblacion)'),
(1, 'Barangay 9 (Poblacion)'),
(1, 'Barangay 10 (Poblacion)'),
(1, 'Barangay 11 (Poblacion)'),
(1, 'Barangay 12 (Poblacion)'),
(1, 'Barangay 13 (Poblacion)'),
(1, 'Barangay 14 (Poblacion)'),
(1, 'Barangay 15 (Poblacion)'),
(1, 'Barangay 16 (Poblacion)'),
(1, 'Barangay 17 (Poblacion)'),
(1, 'Barangay 18 (Poblacion)'),
(1, 'Barangay 19 (Poblacion)'),
(1, 'Barangay 20 (Poblacion)'),
(1, 'Barangay 21 (Poblacion)'),
(1, 'Barangay 22 (Poblacion)'),
(1, 'Barangay 23 (Poblacion)'),
(1, 'Barangay 24 (Poblacion)'),
(1, 'Bilogo'),
(1, 'Bolbok'),
(1, 'Bukal'),
(1, 'Calicanto'),
(1, 'Catandala'),
(1, 'Concepcion'),
(1, 'Conde Itaas'),
(1, 'Conde Labak'),
(1, 'Cuta'),
(1, 'Dalig'),
(1, 'Dela Paz'),
(1, 'Dela Paz Pulot Aplaya'),
(1, 'Dela Paz Pulot Itaas'),
(1, 'Domoclay'),
(1, 'Dumantay'),
(1, 'Gulod Itaas'),
(1, 'Gulod Labak'),
(1, 'Haligue Kanluran'),
(1, 'Haligue Silangan')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(1, 'Ilihan'),
(1, 'Isla Verde'),
(1, 'Kumba'),
(1, 'Kumintang Ibaba'),
(1, 'Kumintang Ilaya'),
(1, 'Libjo'),
(1, 'Liponpon'),
(1, 'Maapas'),
(1, 'Mabacong (Matoco)'),
(1, 'Mahabang Dahilig'),
(1, 'Mahabang Parang'),
(1, 'Mahacot Kanluran'),
(1, 'Mahacot Silangan'),
(1, 'Malalim'),
(1, 'Malibayo'),
(1, 'Malitam'),
(1, 'Maruclap'),
(1, 'Pagkilatan'),
(1, 'Paharang Kanluran'),
(1, 'Paharang Silangan'),
(1, 'Pallocan Kanluran'),
(1, 'Pallocan Silangan'),
(1, 'Pinamucan'),
(1, 'Pinamucan Ibaba'),
(1, 'Pinamucan Silangan'),
(1, 'Sampaga'),
(1, 'San Agapito'),
(1, 'San Agustin Kanluran'),
(1, 'San Agustin Silangan'),
(1, 'San Andres'),
(1, 'San Antonio'),
(1, 'San Isidro'),
(1, 'San Jose Sico'),
(1, 'San Miguel'),
(1, 'San Pedro'),
(1, 'Santa Clara'),
(1, 'Santa Rita Aplaya'),
(1, 'Santa Rita Karsada'),
(1, 'Santo Domingo'),
(1, 'Santo Niño'),
(1, 'Simlong'),
(1, 'Sirang Lupa'),
(1, 'Sorosoro Ibaba'),
(1, 'Sorosoro Ilaya'),
(1, 'Sorosoro Karsada'),
(1, 'Tabangao Ambulong'),
(1, 'Tabangao Aplaya (Tabangao Proper)'),
(1, 'Tabangao Dao'),
(1, 'Talahib Pandayan'),
(1, 'Talahib Payapa')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(1, 'Talumpok Kanluran'),
(1, 'Talumpok Silangan'),
(1, 'Tinga Itaas'),
(1, 'Tinga Labak'),
(1, 'Tulo'),
(1, 'Wawa')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO city (city_id, name) VALUES (2, 'Calaca City')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(2, 'Baclas'),
(2, 'Bagong Tubig'),
(2, 'Balimbing'),
(2, 'Bambang'),
(2, 'Barangay 1 (Poblacion)'),
(2, 'Barangay 2 (Poblacion)'),
(2, 'Barangay 3 (Poblacion)'),
(2, 'Barangay 4 (Poblacion)'),
(2, 'Barangay 5 (Poblacion)'),
(2, 'Barangay 6 (Poblacion)'),
(2, 'Bisaya'),
(2, 'Cahil'),
(2, 'Calantas'),
(2, 'Caluangan'),
(2, 'Camastilisan'),
(2, 'Coral Ni Bacal'),
(2, 'Coral Ni Lopez (Sugod)'),
(2, 'Dacanlao'),
(2, 'Dila'),
(2, 'Loma'),
(2, 'Lumbang Calzada'),
(2, 'Lumbang Na Bata'),
(2, 'Lumbang Na Matanda'),
(2, 'Madalunot'),
(2, 'Makina'),
(2, 'Matipok'),
(2, 'Munting Coral'),
(2, 'Niyugan'),
(2, 'Pantay'),
(2, 'Puting Bato East'),
(2, 'Puting Bato West'),
(2, 'Puting Kahoy'),
(2, 'Quisumbing'),
(2, 'Salong'),
(2, 'San Rafael'),
(2, 'Sinisian'),
(2, 'Taklang Anak'),
(2, 'Talisay'),
(2, 'Tamayo'),
(2, 'Timbain')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO city (city_id, name) VALUES (3, 'Lipa City')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(3, 'Adya'),
(3, 'Anilao'),
(3, 'Anilao-Labac'),
(3, 'Antipolo Del Norte'),
(3, 'Antipolo Del Sur'),
(3, 'Bagong Pook'),
(3, 'Balintawak'),
(3, 'Banaybanay'),
(3, 'Bolbok'),
(3, 'Bugtong na Pulo'),
(3, 'Bulacnin'),
(3, 'Bulaklakan'),
(3, 'Calamias'),
(3, 'Cumba'),
(3, 'Dagatan'),
(3, 'Duhatan'),
(3, 'Halang'),
(3, 'Inosloban'),
(3, 'Kayumanggi'),
(3, 'Latag'),
(3, 'Lodlod'),
(3, 'Lumbang'),
(3, 'Mabini'),
(3, 'Malagonlong'),
(3, 'Malitlit'),
(3, 'Marauoy'),
(3, 'Mataas Na Lupa'),
(3, 'Munting Pulo'),
(3, 'Pagolingin Bata'),
(3, 'Pagolingin East'),
(3, 'Pagolingin West'),
(3, 'Pangao'),
(3, 'Pinagkawitan'),
(3, 'Pinagtongulan'),
(3, 'Plaridel'),
(3, 'Poblacion Barangay 1-8'),
(3, 'Poblacion Barangay 9'),
(3, 'Poblacion Barangay 9-A'),
(3, 'Poblacion Barangay 10-12'),
(3, 'Pusil'),
(3, 'Quezon'),
(3, 'Rizal'),
(3, 'Sabang'),
(3, 'Sampaguita'),
(3, 'San Benito'),
(3, 'San Carlos'),
(3, 'San Celestino'),
(3, 'San Francisco'),
(3, 'San Guillermo'),
(3, 'San Jose')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(3, 'San Lucas'),
(3, 'San Salvador'),
(3, 'San Sebastian (Balagbag)'),
(3, 'Santo Niño'),
(3, 'Santo Toribio'),
(3, 'Sapac'),
(3, 'Sico'),
(3, 'Talisay'),
(3, 'Tambo'),
(3, 'Tangob'),
(3, 'Tanguay'),
(3, 'Tibig'),
(3, 'Tipacan')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO city (city_id, name) VALUES (4, 'Santo Tomas City')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(4, 'Barangay I (Poblacion)'),
(4, 'Barangay II (Poblacion)'),
(4, 'Barangay III (Poblacion)'),
(4, 'Barangay IV (Poblacion)'),
(4, 'San Agustin'),
(4, 'San Antonio'),
(4, 'San Bartolome'),
(4, 'San Felix'),
(4, 'San Fernando'),
(4, 'San Francisco'),
(4, 'San Isidro Norte'),
(4, 'San Isidro Sur'),
(4, 'San Joaquin'),
(4, 'San Jose'),
(4, 'San Juan'),
(4, 'San Luis'),
(4, 'San Miguel'),
(4, 'San Pablo'),
(4, 'San Pedro'),
(4, 'San Rafael'),
(4, 'San Roque'),
(4, 'San Vicente'),
(4, 'Santa Ana'),
(4, 'Santa Anastacia'),
(4, 'Santa Clara'),
(4, 'Santa Cruz'),
(4, 'Santa Elena'),
(4, 'Santa Maria'),
(4, 'Santa Teresita'),
(4, 'Santiago')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO city (city_id, name) VALUES (5, 'Tanauan City')
ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO barangay (city_id, name) VALUES
(5, 'Altura Bata'),
(5, 'Altura Matanda'),
(5, 'Altura-South'),
(5, 'Ambulong'),
(5, 'Bagbag'),
(5, 'Bagumbayan'),
(5, 'Balele'),
(5, 'Banadero'),
(5, 'Banjo East'),
(5, 'Banjo Laurel (Banjo West)'),
(5, 'Bilog-bilog'),
(5, 'Boot'),
(5, 'Cale'),
(5, 'Darasa'),
(5, 'Gonzales'),
(5, 'Hidalgo'),
(5, 'Janopol'),
(5, 'Janopol Oriental'),
(5, 'Laurel'),
(5, 'Luyos'),
(5, 'Mabini'),
(5, 'Malaking Pulo'),
(5, 'Maria Paz'),
(5, 'Maugat'),
(5, 'Montaña (Ik-ik)'),
(5, 'Natatas'),
(5, 'Pagaspas'),
(5, 'Pantay Bata'),
(5, 'Pantay Matanda'),
(5, 'Poblacion Barangay 1'),
(5, 'Poblacion Barangay 2'),
(5, 'Poblacion Barangay 3'),
(5, 'Poblacion Barangay 4'),
(5, 'Poblacion Barangay 5'),
(5, 'Poblacion Barangay 6'),
(5, 'Poblacion Barangay 7'),
(5, 'Sala'),
(5, 'Sambat'),
(5, 'San Jose'),
(5, 'Santol (Doña Jacoba Garcia)'),
(5, 'Santor'),
(5, 'Sulpoc'),
(5, 'Suplang'),
(5, 'Talaga'),
(5, 'Tinurik'),
(5, 'Trapiche'),
(5, 'Ulango'),
(5, 'Wawa')
ON DUPLICATE KEY UPDATE name = VALUES(name);

-- Cities: 5, Barangays: 287
